version: 0.2
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=aws_new  -Dsonar.organization=aws_new -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=129287299e717638c401789025bcb4397807d312 
